version: "3"

services:
  postgres:
    image: postgres:10-alpine
    env_file: .env.production
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  
  memcached:
    image: memcached:1.5.12-alpine
    restart: always
    ports:
      - 11211:11211

  subreddit-gen:
    build: ./
    env_file: .env.production
    volumes:
      - ./:/usr/src/app
    ports:
      - 127.0.0.1:5000:80
    depends_on:
      - memcached
      - postgres
