version: "3"

services:
  db:
    image: postgres:10-alpine
    env_file: .env
    restart: always
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  redis:
    image: redis:5.0-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./.redis:/data
    ports:
      - 6379:6379

  celery:
    build: ./
    restart: always
    env_file: .env
    environment:
      - EBOOKS_USING_DOCKER=1 
    command: celery -A alien_ebooks.celery worker -l info
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis

  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - EBOOKS_USING_DOCKER=1 
    volumes:
      - ./:/usr/src/app
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - db
      - redis
      - celery
